[log]
name=mineru_parser_split_xc
path=./log/mineru_parser_split.log

[iobs]
get_url=http://unihub-stg.paic.com.cn/stg-api/gateway/ksp-backend/iobs/getUrl

[upload]
get_url=http://unihub-stg.paic.com.cn/stg-api/gateway/ksp-backend/iobs/uploadAgentFile

[vlm_image_parse]
serviceId=sQAAZrjvCHr
privateKey=308204BD020100300D06092A864886F70D0101010500048204A7308204A3020100028201010092C1AF4593B0A60C7E7CF00772AD3E9D8BD22085B25805BD
# serviceId=ogAAAZksj0Ti
# privateKey=308204BE020100300D06092A864886F70D0101010500048204A8308204A40201000282010100893CBCE41F3540A432E5A2475B64BA407243A6A9A3B11

[mq]
group_id=PID_ICORE_AAS_PPT_PARSER_SPLIT_XC
topic=T_ICORE_AAS_DOCUMENT_SPLIT_RESULT_XC

[agent_api]
tokenUrl=http://ksp-api-gateway.unihub-stg.paic.com.cn/token/apply
chatUrl=http://ksp-api-gateway.unihub-stg.paic.com.cn/api/chat
taskUrl=http://ksp-api-gateway.unihub-stg.paic.com.cn/api/task

[mineru_api]
app_key=GgUKrcMKkiZAsTpqrkPRyjUWtKWrsie4
app_secret=prL2QALknow7ak3woQM7YdMgYYxZ5oQ
rsaPrivateKey=308204BD020100300D06092A864886F70D0101010500048204A7308204A302010002820101008B1017EEB3CEB5DAC98DA3353118391FF00F840D6D7CA547
url_dialog=http://eagw-gateway-sf-stg.paic.com.cn:80/pingan/bigModel/api/v1/chat/completions
scene_id=1503
openApiCredential=CRE00000187

[pic_url_temp]
pic_url=http://unihub-stg.paic.com.cn/stg-api/gateway/ksp-backend/iobs/icore-aas-ksp-sf-stg-pri/{}?X-Portal-Token=abb233940d2ff469747519c745